// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy232W27phWz9PeA9uSq1I7Ieyhre-Vcs',
    appId: '1:219447894242:web:d786d38d7cae5620613ebb',
    messagingSenderId: '219447894242',
    projectId: 'maid-8d90a',
    authDomain: 'maid-8d90a.firebaseapp.com',
    storageBucket: 'maid-8d90a.appspot.com',
    measurementId: 'G-G8KH47648C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP1IfbrTP0FFpcxmOHBfQtva3Ce7OybrI',
    appId: '1:219447894242:android:2a63a7e12f019a5a613ebb',
    messagingSenderId: '219447894242',
    projectId: 'maid-8d90a',
    storageBucket: 'maid-8d90a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-K_m4uT-M0jtl97bLXn87jWNRZOHp2fQ',
    appId: '1:219447894242:ios:66b2acf462b7101d613ebb',
    messagingSenderId: '219447894242',
    projectId: 'maid-8d90a',
    storageBucket: 'maid-8d90a.appspot.com',
    iosBundleId: 'com.example.maid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-K_m4uT-M0jtl97bLXn87jWNRZOHp2fQ',
    appId: '1:219447894242:ios:df593af643283ac2613ebb',
    messagingSenderId: '219447894242',
    projectId: 'maid-8d90a',
    storageBucket: 'maid-8d90a.appspot.com',
    iosBundleId: 'com.example.maid.RunnerTests',
  );
}
